'''
Created on Jan 31, 2017

@author: mwest

Some radio stations display, or are known by, call signs other than the ones assigned by the FCC. The dictionary and
function below exchange official FCC call signs for the ones the stations is better know by. This can occur for several reasons but
often a station is an AM or FM repeater or translator for a parent station or it could be a branding decision by the owners.
'''

aka_call_signs = {
    'WBRK': 'WFAN'
    , 'KZZQ': 'KZNS'
    , 'W237CW-FX': 'WDAE-FM'
    , 'KSPN': 'ESPNLA'
    , 'K238BF': 'KPYN-FM'
    , 'K265DV': 'KTON-FM'
    , 'KIRO': 'ESPN Seattle'
    , 'K271AH': 'KAPS-FM'
    , 'WFAN': 'The FAN'
    , 'WFAN-FM': 'The FAN FM'
    , 'WIII': 'I-100'
    , 'W262AD': 'I-100'
    , 'WBGG': 'ESPN Pittsburgh'
    , 'W287CP': 'WYTS-FM'
    , 'WBIZ': 'The Brew'
    , 'WBIZ-FM': 'Z-100'
    , 'KKUU-FM': 'ESPN FM'
    ,  "KTZN" : "550 The Zone"
    ,  "KCBF" : "KCBF 820 Sports"
    ,  "KINY" : "KINY-AM"
    ,  "KTKU" : "KTKU-FM"
    ,  "KVOK" : "560 AM Pure Country"
    ,  "KSLD" : "1140 ESPN"
    ,  "WNSP" : "Sports Radio 105.5"
    ,  "WJOX" : "Jox 94.5 FM"
    ,  "WERC" : "News Radio 960/105.5"
    ,  "WERC" : "News Radio 960/105.5"
    ,  "WJOX" : "690 The Fan"
    ,  "WZNN" : "97.3 The Zone"
    ,  "WJQX" : "ESPN Jox 2"
    ,  "WDJC" : "WDJC-FM"
    ,  "WWTM" : "ESPN 1400 Sports Radio"
    ,  "WAGF" : "WAGF-AM"
    ,  "WEVG" : "WEVG-AM"
    ,  "WBCF" : "WBCF-AM"
    ,  "WHEP" : "WHEP-AM"
    ,  "WUMP" : "Sports Radio 730 The Ump"
    ,  "WVNN" : "WVNN-AM"
    ,  "WVNN" : "WVNN-FM"
    ,  "WMSP" : "Sports Radio 740"
    ,  "WLWI" : "News Radio 1440"
    ,  "WTXK" : "The Ticket"
    ,  "WDXZ" : "The Game"
    ,  "WYTK" : "93.9 The Score"
    ,  "WWIC" : "Real Country Radio"
    ,  "WDGM" : "99.1 Tuscaloosa's Sports Authority"
    ,  "WNPT" : "Tide 102.9"
    ,  "WZZN" : "Sports Radio 97.7 The Zone"
    ,  "KVRC" : "KVRC-AM"
    ,  "KDEL" : "KDEL-FM"
    ,  "KBEU" : "KBEU-FM"
    ,  "KEWI" : "KEWI-AM"
    ,  "KAFN" : "KAFN-AM"
    ,  "KKEG" : "98.3 The Keg"
    ,  "KWPS" : "ESPN WPS"
    ,  "KASR" : "Arkansas Sports Radio"
    ,  "KAGH" : "KAGH-AM"
    ,  "KCJF" : "103.9 FM The Game"
    ,  "KQSM" : "92.1 The Ticket"
    ,  "KXJK" : "KXJK News Talk Sports 950"
    ,  "KHGG" : "The Sports Hog"
    ,  "KHGG" : "The Sports Hog"
    ,  "KWHN" : "KWHN-AM"
    ,  "KLSZ" : "100.7 The Ticket"
    ,  "KURM" : "KURM-FM"
    ,  "KYXK" : "KYXK-FM"
    ,  "KAKS" : "The Hog"
    ,  "KEGI" : "100.5 The Eagle"
    ,  "KNEA" : "KNEA-AM"
    ,  "KABZ" : "103.7 The Buzz"
    ,  "KZYP" : "KZYP-AM"
    ,  "KBCN" : "KBCN-FM"
    ,  "KTTG" : "KTTG-FM"
    ,  "KNAS" : "KNAS-FM"
    ,  "KWLT" : "KWLT-FM"
    ,  "KARV" : "KARV-FM"
    ,  "KYYO" : "KYYO-FM"
    ,  "KURM" : "KURM-AM"
    ,  "KARV" : "KARV-AM"
    ,  "KUOA" : "The Hog"
    ,  "KTRG" : "ESPN 94.1"
    ,  "KXFF" : "Sports Radio 106.1"
    ,  "KVNA" : "KVNA-AM"
    ,  "KGME" : "XTRA Sports 910"
    ,  "KZUA" : "Wild West Country"
    ,  "KNTR" : "KNTR Sports"
    ,  "KDUS" : "NBC Sports Radio 1060"
    ,  "KTAR" : "KTAR-AM"
    ,  "KNKI" : "iTalk 106.7 FM"
    ,  "KDDL" : "Cattle Country"
    ,  "KQNA" : "KQNA-AM"
    ,  "KATO" : "KATO-AM"
    ,  "KAZM" : "KAZM Radio 780 AM"
    ,  "KQFN" : "1580 The Fanatic"
    ,  "KFFN" : "ESPN 1490 The Fan"
    ,  "WQTH" : "104.1 The Truth"
    ,  "KQTH" : "104.1 The Truth"
    ,  "KCUB" : "1290 AM The Source"
    ,  "KTUC" : "KTUC-AM"
    ,  "KXTK" : "ESPN 1280 AM The Ticket"
    ,  "KHTY" : "Fox Sports 970"
    ,  "KBFP" : "Comedy 800"
    ,  "KGEO" : "ESPN Bakersfield"
    ,  "KURY" : "KURY 95.3"
    ,  "KEWE" : "1340 Fox Sports Radio"
    ,  "KCKS" : "Fox Sports Radio 101.7"
    ,  "KXO" : "KXO AM 1230"
    ,  "KEKA" : "101 Thunder Country"
    ,  "KATA" : "ESPN Radio 1340"
    ,  "KCBL" : "FOX Sports Radio 1340 & 1400"
    ,  "KALZ" : "PowerTalk 96.7"
    ,  "KRAK" : "ESPN 910"
    ,  "KRKC" : "KRKC Country 1490 AM"
    ,  "KRKC" : "KRKC-FM"
    ,  "XEPE" : "ESPN Radio 1700 San Diego"
    ,  "KLAC" : "AM 570 Fox Sports LA "
    ,  "KFWB" : "KFWB-AM"
    ,  "KEIB" : "The Patriot"
    ,  "KSPN" : "710 ESPN"
    ,  "KNX" : "KNX 1070 News Radio"
    ,  "KUNK" : "KUNK-FM"
    ,  "KESP" : "ESPN Radio 970"
    ,  "KFIV" : "KFIV 1360"
    ,  "KIDD" : "ESPN 630 KIDD"
    ,  "KYZZ" : "KYZZ-FM"
    ,  "KVON" : "Wine Country News Talk"
    ,  "KTOX" : "KTOX-AM"
    ,  "KRRF" : "106.3 The Surf"
    ,  "KNEW" : "KNEW-AM"
    ,  "KPRL" : "KPRL-AM"
    ,  "KNRO" : "Fox Sports 1670"
    ,  "KKXS" : "KKXS Sports"
    ,  "KLOA" : "KLOA-AM"
    ,  "KMRQ" : "KMRQ-FM"
    ,  "KTDD" : "Fox Sports Radio 1350 AM"
    ,  "KHTK" : "1140 The Fan"
    ,  "KCTC" : "ESPN 1320"
    ,  "KIFM" : "ESPN Radio 1320"
    ,  "KSAC" : "Money 105.5"
    ,  "KHIP" : "The Hippo"
    ,  "KUBE" : "Fox Sports 1350"
    ,  "KLSD" : "Xtra Sports 1360"
    ,  "KNBR" : "KNBR 680 AM The Sports Leader"
    ,  "KGMZ" : "95.7 The Game"
    ,  "KOSF" : "KOSF-FM"
    ,  "KTCT" : "KNBR 1050 The Sports Leader"
    ,  "KWSX" : "Talk Radio 1280"
    ,  "KXPS" : "Team 1010"
    ,  "XPRS" : "XX 1090"
    ,  "KVEN" : "SportsRadio 1450"
    ,  "KRZR" : "FOX Sports Radio 1340 & 1400"
    ,  "CFRN" : "TSN 1260"
    ,  "CKOC" : "TSN 1150"
    ,  "CKGM" : "CKGM-AM"
    ,  "CFGO" : "TSN 1200"
    ,  "CHUM" : "TSN 1050"
    ,  "CFTE" : "TSN 1410"
    ,  "CKST" : "CKST-AM"
    ,  "KALQ" : "KALQ-FM"
    ,  "KNFO" : "KNFO-FM"
    ,  "KBVC" : "KBVC-FM"
    ,  "KSTY" : "Star 104.5"
    ,  "KRDO" : "KRDO News Radio 1240"
    ,  "KRDO" : "KRDO News Radio 105.5"
    ,  "KCSF" : "XTRA Sports 1300"
    ,  "KVOR" : "AM 740 KVOR"
    ,  "KEPN" : "ESPN Radio 1600"
    ,  "KRSJ" : "KRSJ-FM"
    ,  "KIUP" : "KIUP-AM"
    ,  "KSKE" : "KSKE-FM"
    ,  "KRFD" : "KRFD-FM"
    ,  "KJME" : "KJME-AM"
    ,  "KSIR" : "1010 KSIR Farm Radio"
    ,  "KMTS" : "Your Brand of Country"
    ,  "KTMM" : "The Team 1340"
    ,  "KFKA" : "Newstalk 1310 KFKA "
    ,  "KKFN" : "Sports Radio 104.3 The Fan"
    ,  "KWUF" : "Wolf Country"
    ,  "KDZA" : "Homer 1350"
    ,  "KAVA" : "KAVA-AM"
    ,  "KVRH" : "KVRH-AM"
    ,  "KNAM" : "News Radio 1490 "
    ,  "KTYV" : "ESPN RADIO 98.9"
    ,  "KPMX" : "KPMX-FM"
    ,  "KNNG" : "KNNG-FM"
    ,  "KSIK" : "KSIK-FM"
    ,  "KCRT" : "92.5 The Mountain"
    ,  "KSPK" : "KSPK-FM"
    ,  "WLAD" : "WLAD-AM"
    ,  "WTIC" : "NewsTalk 1080"
    ,  "WXLM" : "NewsTalk 980"
    ,  "WPOP" : "FOX Sports Radio 1410"
    ,  "WAVZ" : "ESPN Radio 1300"
    ,  "WINY" : "WINY-AM"
    ,  "WMOS" : "102.3 The Wolf"
    ,  "WUCS" : "97.9 ESPN Radio"
    ,  "WDCH" : "WDCH-FM"
    ,  "WYUS" : "WYUS-AM"
    ,  "WDEL" : "News Talk Radio 1150"
    ,  "WWTX" : "1290 The Ticket"
    ,  "WDEL" : "WDEL-FM"
    ,  "WFLN" : "WFLN-AM"
    ,  "WKFL" : "Kickin Country"
    ,  "WOCY" : "WOCY-FM"
    ,  "WZCC" : "WZCC-AM"
    ,  "WHNR" : "WHNR-AM"
    ,  "WELE" : "Goliath Radio"
    ,  "WPUL" : "WPUL-AM"
    ,  "WNWF" : "WNWF-AM"
    ,  "WWCN" : "Sports Radio 770 ESPN"
    ,  "WJPT" : "Sunny 106"
    ,  "WTKE" : "The Ticket"
    ,  "WBGG" : "WBGG-FM"
    ,  "WFWN" : "1240 The Fan"
    ,  "WFSX" : "WFSX-AM"
    ,  "WWCN" : "99.3 ESPN"
    ,  "WRUF" : "WRUF Sports Radio 850"
    ,  "WYGC" : "105 The Game"
    ,  "WGGG" : "WGGG-AM"
    ,  "WFXJ" : "930 The Fox"
    ,  "WJXL" : "1010 XL"
    ,  "WJXL" : "1010 XL"
    ,  "WUUB" : "ESPN 106.3"
    ,  "WKYZ" : "The New Pirate Radio 101.7"
    ,  "WKWF" : "Sports Radio 1600"
    ,  "WKEY" : "WKEY-FM"
    ,  "WKBX" : "KBAY-106"
    ,  "WHOO" : "ESPN 1080"
    ,  "WFFG" : "WFFG-AM"
    ,  "WGMX" : "Mix 94"
    ,  "WIOD" : "News Radio 610 WIOD"
    ,  "WINZ" : "AM 940 The Sports Animal"
    ,  "WQAM" : "WQAM-AM"
    ,  "WTKE" : "WTKE-AM"
    ,  "WNOG" : "WNOG-AM"
    ,  "WJBX" : "ESPN Deportes 770"
    ,  "WMOP" : "WMOP-AM"
    ,  "WOCA" : "WOCA-AM"
    ,  "WRSO" : "810 CBS Sports"
    ,  "WNZF" : "WNZF-AM"
    ,  "WDIZ" : "ESPN 590"
    ,  "WBSR" : "WBSR-AM"
    ,  "WAMT" : "WAMT-AM"
    ,  "WHBO" : "Sports Talk Florida"
    ,  "WKII" : "1070 NBC Sports Radio"
    ,  "WPSL" : "WPSL-AM"
    ,  "WMEN" : "640 Sports"
    ,  "WSRQ" : "Talk Radio 1220"
    ,  "WENG" : "News Talk 1530"
    ,  "WHFS" : "1010 Sports"
    ,  "WDAE" : "WDAE-AM"
    ,  "WSTU" : "WSTU-AM"
    ,  "WJHC" : "WJHC-FM "
    ,  "WVFT" : "Freedom 93"
    ,  "WVTF" : "WVTF-FM"
    ,  "WNLS" : "1270 The Team"
    ,  "WHFS" : "98.7 The Fan"
    ,  "WWBA" : "News Talk Florida"
    ,  "WKEZ" : "WKEZ-FM"
    ,  "WEFL" : "ESPN 760"
    ,  "WIXC" : "News Talk Florida"
    ,  "WAUC" : "WAUC-AM"
    ,  "WFTL" : "850 WFTL"
    ,  "WBZT" : "1230 The Zone"
    ,  "WZZR" : "Real Radio 94.3"
    ,  "WTSM" : "ESPN Tallahassee"
    ,  "WSRA" : "WSRA-AM"
    ,  "WGPC" : "1450 The Fan"
    ,  "WRFC" : "960 The Ref"
    ,  "WQXI" : "Sports Radio 790 The Zone"
    ,  "WZGC" : "92.9 The Game"
    ,  "WAOK" : "WAOK-AM"
    ,  "WGAC" : "WGAC-AM "
    ,  "WGAC" : "WGAC-FM "
    ,  "WRDW" : "WRDW-AM "
    ,  "WFNS" : "The Fan Sports Radio 1350"
    ,  "WSFN" : "The Fan 790"
    ,  "WDUN" : "News Talk 102.9"
    ,  "WGHC" : "WGHC-AM"
    ,  "WIOL" : "1580 The Zone"
    ,  "WIOL" : "The Zone"
    ,  "WCON" : "WCON-FM"
    ,  "WDBG" : "BIG 103.1"
    ,  "WMLT" : "WMLT-AM"
    ,  "WDUN" : "WDUN-AM"
    ,  "WGGA" : "ESPN Radio 1240 The Ticket"
    ,  "WKEU" : "The Rock 88.9 FM/ 1450 AM"
    ,  "WKEU" : "The Rock 88.9 FM/ 1450 AM"
    ,  "WHIE" : "WHIE-AM"
    ,  "WIFO" : "Big Dog Country"
    ,  "WLOP" : "The Buzz 1370"
    ,  "WPEH" : "WPEH-AM"
    ,  "WMAC" : "WMAC-AM"
    ,  "WFOM" : "1230 The Fan 2"
    ,  "WBMZ" : "WBMZ-FM "
    ,  "WMVG" : "1450 The Home Team"
    ,  "WALH" : "WALH-AM"
    ,  "WCNN" : "680 The Fan"
    ,  "WZBX" : "WZBX-FM"
    ,  "WGJK" : "1360 The Jock"
    ,  "WRGA" : "WRGA-AM"
    ,  "WZAT" : "102.1 ESPN Radio"
    ,  "WSEG" : "Star 1400 & 104.3"
    ,  "WIXV" : "I-95 The Rock of Savannah"
    ,  "WJLG" : "900 The Ticket"
    ,  "WPTB" : "WPTB-AM"
    ,  "WJAT" : "WJAT-AM"
    ,  "WTIF" : "107.5 Hometown Country"
    ,  "WJEM" : "The Jock 1150"
    ,  "WAYX" : "WAYX-AM"
    ,  "WCJM" : "The Bull 100.9"
    ,  "WJXY" : "93.9 The Team"
    ,  "KMWB" : "B93"
    ,  "KPUA" : "KPUA-AM"
    ,  "KHLO" : "ESPN Hawaii"
    ,  "KNWB" : "B97"
    ,  "KKEA" : "ESPN 1420"
    ,  "KKON" : "ESPN Hawaii"
    ,  "KHKA" : "The Team 1500 AM"
    ,  "KAOI" : "KAOI-AM"
    ,  "KIIC" : "Thunder Country"
    ,  "KCPS" : "KCPS Talk Radio 1150 AM"
    ,  "KCNZ" : "1650 The Fan"
    ,  "KDNZ" : "KDNZ-AM"
    ,  "KGYM" : "1600 ESPN Sports Radio"
    ,  "KROS" : "1340 AM KROS"
    ,  "KSIB" : "KSIB-AM"
    ,  "KXNO" : "1460 KXNO"
    ,  "KBGG" : "1700 The Champ"
    ,  "KWQW" : "98.3 The Vibe"
    ,  "KGRN" : "KGRN-AM "
    ,  "KXLQ" : "1490 The Jock"
    ,  "KGLO" : "KGLO-AM"
    ,  "KRIB" : "KRIB-AM"
    ,  "KWIA" : "KWIA-FM"
    ,  "KMA" : "KMA-AM"
    ,  "KMNS" : "FOX Sports 620 KMNS"
    ,  "KSCJ" : "KSCJ-AM"
    ,  "KBLI" : "KBLI-AM"
    ,  "KEII" : "KEII-AM"
    ,  "KTIK" : "1350 KTIK The Ticket"
    ,  "KTIK" : "93.1 KTIK The Ticket"
    ,  "KIDO" : "Sports Radio 630"
    ,  "KFXD" : "630 The Fan"
    ,  "KKGL" : "96.9 The Eagle"
    ,  "KVNI" : "KVNI-AM"
    ,  "KBLY" : "KBLY-AM"
    ,  "KEIR" : "KEIR-AM"
    ,  "KART" : "KART-AM"
    ,  "KZBG" : "Big Country 97.7"
    ,  "KRPL" : "KRPL-AM"
    ,  "KSEI" : "930 The Cruise"
    ,  "KZNO" : "KZON-AM"
    ,  "KZNO" : "KZNO-FM"
    ,  "WBIG" : "WBIG-AM"
    ,  "WTJK" : "ESPN 1380"
    ,  "WJBC" : "FM 93.7 WJBC"
    ,  "WJBC" : "AM 1230 WJBC"
    ,  "WZIM" : "99.5 The Ticket"
    ,  "WRJM" : "WRJM-AM"
    ,  "WSCR" : "670 The Score"
    ,  "WMVP" : "ESPN 1000"
    ,  "WLUP" : "97.9 The Loop"
    ,  "WGWG" : "87.7 The Game"
    ,  "WGN" : "Radio 720 WGN"
    ,  "WLS" : "WLS-AM"
    ,  "WYLL" : "WYLL-AM"
    ,  "WXLT" : "103.5 ESPN Southern Illinois"
    ,  "WDAN" : "WDAN-AM"
    ,  "WDZ" : "ESPN 1050 The Fan"
    ,  "WYDS" : "WYDS-FM"
    ,  "WZUS" : "Talk 101"
    ,  "WZNX" : "106.7 The Fox"
    ,  "WCRA" : "WCRA-AM 1090"
    ,  "WHQQ" : "WHQQ-FM"
    ,  "WGCY" : "WGCY-FM"
    ,  "WKXQ" : "WKXQ 92.5 FM All-American Radio"
    ,  "WVIL" : "WVIL FM 101.3"
    ,  "WLDS" : "WLDS-AM"
    ,  "WKEI" : "WKEI 1450"
    ,  "WLMD" : "WLMD-FM"
    ,  "WGGH" : "WGGH-AM"
    ,  "WMOK" : "Real Country"
    ,  "WEFM" : "WEFM-FM"
    ,  "WYFX" : "WYFX 106.7 FM"
    ,  "WMIX" : "WMIX-FM"
    ,  "WZPN" : "95.5 ESPN Peoria"
    ,  "KJOC" : "ESPN Quad Cities"
    ,  "WTAD" : "AM 930 News Talk Radio"
    ,  "WTAY" : "WTAY-AM"
    ,  "WRHL" : "WRHL-AM"
    ,  "WLUV" : "WLUV-AM"
    ,  "WJBD" : "WJBD-FM"
    ,  "WCCI" : "WCCI 100.3 FM"
    ,  "WTIM" : "WTIM-AM"
    ,  "WMAY" : "970 AM WMAY"
    ,  "WSDR" : "WSDR-AM"
    ,  "WTIM" : "Newstalk 97.3"
    ,  "WMKR" : "WMKR-FM"
    ,  "WPMB" : "WPMB-AM"
    ,  "WHET" : "WHET-FM"
    ,  "WYKT" : "105.5 The Kat"
    ,  "KFNS" : "590 The Fan"
    ,  "WBIW" : "1340 AM WBIW"
    ,  "WZBD" : "Adams County Radio"
    ,  "WGCL" : "News Talk 1370"
    ,  "WSDM" : "WSDM-FM"
    ,  "WSDX" : "WSDX-AM"
    ,  "WHON" : "930 WHON"
    ,  "WRZQ" : "WRZQ-FM"
    ,  "WCDQ" : "True Country 106.3"
    ,  "WGBF" : "NewsTalk 1280"
    ,  "WJLT" : "ESPN Evansville"
    ,  "WKJG" : "ESPN Radio 1380"
    ,  "WLKI" : "FM's Best"
    ,  "WOWO" : "News Talk 1190"
    ,  "WXLW" : "XL 950 Sportstalk"
    ,  "WGL" : "1250 The Ticket"
    ,  "WREB" : "WREB 94.3 FM"
    ,  "WJOB" : "WJOB-AM"
    ,  "WFGA" : "WFGA-FM"
    ,  "WBDC" : "WBDC-FM"
    ,  "WNDE" : "SportsRadio 1260"
    ,  "WFBQ" : "Q95"
    ,  "WFNI" : "1070 The Fan"
    ,  "WIBC" : "WIBC-FM"
    ,  "WIOU" : "WIOU-AM"
    ,  "WASK" : "ESPN 1450 AM"
    ,  "WRZR" : "94.5 The Razor"
    ,  "WORX" : "WORX-FM"
    ,  "WBAT" : "WBAT-AM"
    ,  "WMRI" : "860 ESPN Radio"
    ,  "WAOR" : "102.7 The Fan"
    ,  "WLTI" : "WLTI-AM"
    ,  "WNIL" : "WNIL-AM"
    ,  "WLME" : "102.7 The Game"
    ,  "WPGW" : "WPGW-AM"
    ,  "WPGW" : "WPGW-FM"
    ,  "WSJD" : "WSJD-FM"
    ,  "WKBV" : "WKBV-AM"
    ,  "WARU" : "WARU-FM"
    ,  "WAXL" : "WAXL-FM"
    ,  "WLCL" : "WLCL-FM"
    ,  "WSBT" : "News Radio 960"
    ,  "WBOW" : "WBOW-AM"
    ,  "WAOV" : "WAOV 1450"
    ,  "WZDM" : "Wisdom 92.1 FM"
    ,  "WJOT" : "WJOT-AM"
    ,  "WJOT" : "105.9 The Bash"
    ,  "WRSW" : "ESPN Radio 1480"
    ,  "WLEG" : "ESPN Warsaw"
    ,  "WWBL" : "Real Country WWBL The Bullet"
    ,  "KEOJ" : "KEOJ-FM"
    ,  "KFH" : "Sports Radio 98.7 & 1240"
    ,  "KSHQ" : "ESPN 100.7"
    ,  "KVOE" : "KVOE 1400"
    ,  "KQYX" : "KQYX-AM "
    ,  "KIUL" : "News Radio 1240 KIUL"
    ,  "KGGS" : "KGGS-AM"
    ,  "KKCI" : "KKCI-FM"
    ,  "KAYS" : "14 KAYS"
    ,  "KWBW" : "KMBW 1450 AM"
    ,  "WHB" : "Sports Radio 810 WHB"
    ,  "KGBL" : "100.9 The Bull"
    ,  "KLWN" : "KLWN-AM"
    ,  "KMAN" : "Newstalk 1350 K-Man"
    ,  "KXNC" : "Kiss 104.7"
    ,  "KLKC" : "KLKC Radio"
    ,  "KSEK" : "99.1 ESPN The Ticket"
    ,  "KSAL" : "News Radio 1150 KSAL"
    ,  "KDJM" : "Real Country 101.7"
    ,  "KYUL" : "News Radio 1310"
    ,  "WIBW" : "WIBW-AM"
    ,  "KTOP" : "Sports Radio 1490"
    ,  "KDVV" : "V-100"
    ,  "KFH" : "Sports Radio 1240 & 98.7"
    ,  "KGSO" : "KGSO Sports Radio"
    ,  "WCMI" : "ESPN Radio 1340"
    ,  "WDGG" : "93.7 The Dawg"
    ,  "WCCK" : "WCCK-FM"
    ,  "WCMI" : "Planet 92.7"
    ,  "WAIN" : "WAIN-FM"
    ,  "WTUV" : "WTUV-FM"
    ,  "WCDS" : "WCDS-AM"
    ,  "WWKU" : "ESPN Radio 1450"
    ,  "WSON" : "WSON 860 AM"
    ,  "WHOP" : "NewsTalk 1230"
    ,  "WLXG" : "Sports Radio 1300"
    ,  "WLXO" : "Hank 96.1"
    ,  "WHBE" : "ESPN 105.7"
    ,  "WHAS" : "News Talk 840"
    ,  "WNBS" : "1340 WNBS"
    ,  "WOFC" : "ESPN 1130"
    ,  "WHBE" : "ESPN Radio 680"
    ,  "WPAD" : "1560 The Fan"
    ,  "WKYH" : "WKYH-AM"
    ,  "WBTH" : "WBTH-AM"
    ,  "WLSI" : "ESPN Radio 900"
    ,  "WPRT" : "ESPN Radio 960"
    ,  "KDBS" : "KDBS"
    ,  "WNXX" : "104.5 ESPN Radio"
    ,  "WUBR" : "CBS Sports Radio 910"
    ,  "KNBB" : "ESPN Radio 97.7"
    ,  "KBEF" : "KBEF-FM"
    ,  "KXMG" : "Mega 107.5"
    ,  "KPEL" : "ESPN 1420 AM"
    ,  "KLWB" : "103.7 The Game"
    ,  "KXZZ" : "Sports Radio 1580"
    ,  "KEZM" : "Sports Radio 1310"
    ,  "KLRZ" : "KLRZ-FM"
    ,  "KANE" : "KANE-AM"
    ,  "WWL" : "WWL-AM"
    ,  "WWL" : "WWL-FM"
    ,  "WWWL" : "ESPN 1350"
    ,  "KEEL" : "KEEL News Radio 710"
    ,  "KWKH" : "1130 AM KWKH"
    ,  "KRMD" : "KRMD-AM"
    ,  "KVPI" : "Oldies 92.5"
    ,  "KNCB" : "The Sports Rebel"
    ,  "WEEI" : "Sports Radio WEEI"
    ,  "WEEI" : "WEEI-FM"
    ,  "WMKK" : "Sportsradio WEEI 93.7-FM/850-AM"
    ,  "WRKO" : "AM 680 WRKO"
    ,  "WWZN" : "AM 1510"
    ,  "WXKS" : "Bloomberg Radio"
    ,  "WJMN" : "JAM'N 94.5"
    ,  "WBZ" : "98.5 The Sports Hub"
    ,  "WSAR" : "WSAR-AM"
    ,  "WPKZ" : "WPKZ-AM 1280"
    ,  "WPVQ" : "Bear Country 95.3"
    ,  "WEII" : "96.3 FM Cape Cod"
    ,  "WMRC" : "WMRC-AM"
    ,  "WBSM" : "WBSM-AM"
    ,  "WBEC" : "WBEC-AM"
    ,  "WNAW" : "WNAW-AM"
    ,  "WWEI" : "WWEI-FM"
    ,  "WXTK" : "News Radio 95"
    ,  "WVEI" : "Sports Radio 1440 WVEI"
    ,  "WVEI" : "Sports Radio 105.5 WEEI-FM"
    ,  "WNAV" : "1430 WNAV - Your Hometown Station"
    ,  "WJZ" : "105.7 The Fan"
    ,  "WJZ" : "ESPN Radio 1300"
    ,  "WBAL" : "WBAL-AM"
    ,  "WNST" : "WNST-AM"
    ,  "WWMX" : "Mix 106.5"
    ,  "WSPZ" : "Sports Talk 570"
    ,  "WTEM" : "ESPN 980"
    ,  "WWXT" : "Triple-X ESPN Radio"
    ,  "WFRB" : "Talk Radio 560"
    ,  "WTBO" : "WTBO 1450"
    ,  "WCMD" : "ESPN Radio 1230"
    ,  "WRNR" : "WRNR-FM"
    ,  "WARK" : "WARK-AM"
    ,  "WCBC" : "WCBC-FM"
    ,  "WMDM" : "97.7 The Rocket"
    ,  "WIJK" : "WIJK-AM"
    ,  "WGOP" : "WGOP-AM"
    ,  "WTGM" : "960 The Sports Animal"
    ,  "WICO" : "WICO-FM"
    ,  "WTHU" : "WTHU-AM"
    ,  "WJFK" : "CBS Sports Radio 1580"
    ,  "WJFK" : "106.7 The Fan"
    ,  "WNEW" : "WNEW-FM"
    ,  "WTTR" : "WTTR-AM"
    ,  "WEBB" : "B98.5"
    ,  "WZON" : "AM 620 WZON The Pulse"
    ,  "WEZQ" : "92.9 The Ticket"
    ,  "WPPI" : "WPPI-FM"
    ,  "WHTB" : "WHTB-AM 1400"
    ,  "WTBM" : "OXO Country"
    ,  "WOXO" : "OXO Country"
    ,  "WZAN" : "970 WZAN"
    ,  "WJJB" : "The Big Jab"
    ,  "WTME" : "WTME-AM"
    ,  "WSHK" : "WSHK-FM"
    ,  "WEGP" : "Talk of the Country 1390"
    ,  "WPEI" : "WPEI-FM"
    ,  "WWNZ" : "WWNZ-AM"
    ,  "WTVL" : "WTVL-AM"
    ,  "WFYC" : "WFYC-AM"
    ,  "WTKA" : "Sports Talk 1050"
    ,  "WLBY" : "Talk 1290"
    ,  "WSJM" : "News Talk 94.9"
    ,  "WNEM" : "NewsRadio 1250"
    ,  "WKAD" : "WKAD-FM"
    ,  "WXYT" : "97.1 The Ticket"
    ,  "WXYT" : "Talk Radio 1270"
    ,  "WDFN" : "1130 The Fan"
    ,  "WMGC" : "Detroit Sports 105.1"
    ,  "WVFN" : "The Game 730AM"
    ,  "WGLQ" : "Magic 97"
    ,  "WCHT" : "NewsTalk Radio 600"
    ,  "WMPA" : "WMPA-FM"
    ,  "WFNT" : "WFNT-AM"
    ,  "WTRX" : "Sports Xtra 1330"
    ,  "WSRT" : "WSRT-FM"
    ,  "WGHN" : "Sports Radio 1370"
    ,  "WGHN" : "WGHN-FM"
    ,  "WBBL" : "WBBL-FM"
    ,  "WTKG" : "Talk Alternative AM 1230"
    ,  "WBFX" : "101.3 The Fox"
    ,  "WJRW" : "News Talk 1340"
    ,  "WLAV" : "97-LAV Classic Rock"
    ,  "WHTC" : "Holland's Hometown Station"
    ,  "WMAX" : "96.1 ESPN"
    ,  "WSRJ" : "WSRJ-FM"
    ,  "WCCY" : "WCCY"
    ,  "WOBE" : "B100.7 FM "
    ,  "WJMS" : "Real Country US 59"
    ,  "WIBM" : "WIBM-AM"
    ,  "WKHM" : "K105.3"
    ,  "WKZO" : "WKZO-AM"
    ,  "WKZO" : "WKZO-FM"
    ,  "WAGN" : "WAGN-AM"
    ,  "WLUN" : "100.9 ESPN"
    ,  "WMBN" : "1340 The Ticket"
    ,  "WPHM" : "WPHM-AM"
    ,  "WSGW" : "WSGW-AM"
    ,  "WSJM" : "Sports Radio 1400"
    ,  "WBET" : "ESPN Sports Radio 1230"
    ,  "KRJB" : "KRJB-FM"
    ,  "KKIN" : "KKIN-AM"
    ,  "KKIN" : "KKIN-FM"
    ,  "WXCE" : "WXCE-AM"
    ,  "KKLN" : "94.1 The Loon"
    ,  "KKCQ" : "KKCQ-FM"
    ,  "KBUN" : "Sports Radio AM 1450"
    ,  "KPMI" : "News Channel 1300"
    ,  "KKBJ" : "Mix 103.7"
    ,  "WMIS" : "92.1 The River"
    ,  "KBEW" : "KBEW-FM"
    ,  "WRXP" : "The Ticket"
    ,  "KROX" : "The Voice of the Valley"
    ,  "KDLM" : "KDLM 1340 AM"
    ,  "KQDS" : "1490 The Fan"
    ,  "KJOQ" : "KJOQ-AM"
    ,  "WEBC" : "AM 560 WEBC Radio"
    ,  "WGVZ" : "The Ticket"
    ,  "WELY" : "WELY-AM"
    ,  "WELY" : "WELY-FM"
    ,  "KRBT" : "KRBT-AM"
    ,  "KJJK" : "KJJK-AM"
    ,  "KKCQ" : "KKCQ-AM"
    ,  "KMFY" : "KMFY-FM"
    ,  "KOZY" : "KOZY-AM"
    ,  "WWAX" : "92.1 The Fan"
    ,  "WGVX" : "105.1 The Ticket"
    ,  "KLTF" : "Little Falls Radio"
    ,  "KLFT" : "KLFT-AM "
    ,  "KLKS" : "KLKS-FM"
    ,  "KRJM" : "KRJM-FM"
    ,  "KFSP" : "KFSP-AM"
    ,  "KTLK" : "Twin Cities News Talk"
    ,  "KFAN" : "100.3 FM KFAN: The Fan "
    ,  "KFXN" : "KFAN - Sports Radio 100.3"
    ,  "KTCN" : "News Talk AM 1130"
    ,  "KMRS" : "AM 1230"
    ,  "KQYK" : "95.7 The Blaze"
    ,  "KAKK" : "Oldies 1570"
    ,  "KPRM" : "Radio 870 KPRM"
    ,  "KVKK" : "KVKK-AM"
    ,  "KKOK" : "KKOK-FM"
    ,  "WCMP" : "WCMP-AM"
    ,  "WCMP" : "WCMP-FM"
    ,  "WKFX" : "99.1 The Fox"
    ,  "WEVR" : "WEVR-FM"
    ,  "KWEB" : "KFAN AM 1270"
    ,  "KFAN" : "1270 The Fan"
    ,  "KARZ" : "KARZ-FM"
    ,  "WJON" : "AM 1240 WJON Radio"
    ,  "KTRF" : "KTRF-AM"
    ,  "KSKK" : "KSKK-AM The Arrow"
    ,  "KXSS" : "1390 The Fan"
    ,  "KWNO" : "KWNO-FM"
    ,  "KAGE" : "KAGE-AM"
    ,  "KWNO" : "KWNO-AM"
    ,  "KWOA" : "News Radio AM 730 "
    ,  "KAAN" : "KAAN-FM"
    ,  "KAAN" : "KAAN-AM"
    ,  "KKWK" : "KKWK-FM"
    ,  "KMRN" : "KMRN-AM"
    ,  "KGIR" : "KGIR-AM"
    ,  "KTGR" : "ESPN 1580"
    ,  "KTGR" : "ESPN 100.5 FM"
    ,  "KFRU" : "KFRU-AM"
    ,  "KLPW" : "KLPW-FM"
    ,  "KREI" : "KREI-AM"
    ,  "KTJJ" : "KTJJ-FM"
    ,  "KJFF" : "Straight Talk 1400"
    ,  "KCTE" : "Hot Talk 1510"
    ,  "KZJF" : "Sports Radio 104.1 The Fan"
    ,  "KLIK" : "News Talk 1240"
    ,  "WMBH" : "ESPN Joplin"
    ,  "KCXL" : "KCXL-AM"
    ,  "KMAL" : "KMAL-AM"
    ,  "KMMO" : "KMMO 102.9"
    ,  "KMMO" : "KMMO AM 1300"
    ,  "KKBL" : "The Buzz 95.9"
    ,  "KYRO" : "Westplex News Talk 1280"
    ,  "KLSC" : "ESPN 92.9"
    ,  "KBFL" : "KBFL-AM"
    ,  "KBFL" : "KBFL-FM"
    ,  "KWTO" : "Jock 98.7"
    ,  "KWTO" : "NewsTalk 560"
    ,  "KGMY" : "Fox Sports 1400"
    ,  "KXUS" : "US97"
    ,  "KESJ" : "ESPN 1550"
    ,  "KSLG" : "Sports Radio 1380 AM"
    ,  "KMOX" : "News Radio 1120"
    ,  "WXOS" : "101 SPORTS"
    ,  "KXFN" : "1380 The Fan 2"
    ,  "KTKS" : "Lake Radio"
    ,  "KHOM" : "ESPN KHOM 'The Homer'"
    ,  "WSMS" : "99.9 The Fox"
    ,  "WXBD" : "ESPN Sports Radio 1490"
    ,  "WTNI" : "1640 The Champ"
    ,  "WRQO" : "SuperTalk Mississippi"
    ,  "WJWF" : "WJWF-AM 1400"
    ,  "WNMQ" : "103.1 The Team"
    ,  "WKOR" : "WKOR 980 AM"
    ,  "WUJM" : "96.7 The Champ"
    ,  "WGBL" : "WGBL-FM"
    ,  "WHSY" : "WHSY-AM"
    ,  "WDXO" : "WDXO-FM"
    ,  "WSFZ" : "SuperSport 930"
    ,  "WRKS" : "105.9 The Zone"
    ,  "WJQS" : "1400 The Fan"
    ,  "WMXI" : "WMXI-FM"
    ,  "WVGG" : "Talk Radio 1440 AM"
    ,  "WRBE" : "WRBE-FM"
    ,  "WMOX" : "WMOX"
    ,  "WALT" : "WALT-AM"
    ,  "WALT" : "WALT-FM"
    ,  "KBIX" : "The Sports Animal"
    ,  "WMUT" : "WMUT 101.3"
    ,  "WPMO" : "Talk Radio 1580 AM"
    ,  "WHOC" : "WHOC-AM"
    ,  "WRJW" : "WRJW-AM"
    ,  "WJDR" : "WJDR-FM"
    ,  "KBUD" : "Anointed 102.1 KBUD"
    ,  "WSSO" : "WSSO-AM"
    ,  "WXWX" : "WXWX-FM"
    ,  "WVBG" : "NewsTalk 1490 WVBG"
    ,  "WBYP" : "WBYP-FM"
    ,  "KBLG" : "ESPN Sports Radio 910"
    ,  "KYYA" : "News Talk 730"
    ,  "KOBB" : "ESPN 1230"
    ,  "KBOW" : "Country 55"
    ,  "KVMO" : "KVMO-FM"
    ,  "KMON" : "KMON-AM"
    ,  "KMON" : "KMON-FM"
    ,  "KCAP" : "KCAP"
    ,  "KIMO" : "The Mighty Mo"
    ,  "KSAM" : "ESPN Radio 1240 SAM"
    ,  "KGRZ" : "Sports Talk 1450"
    ,  "KYLT" : "KYLT-AM"
    ,  "KSEN" : "KSEN AM 1150 "
    ,  "WSPC" : "1010 WSPC"
    ,  "WYSE" : "ESPN Radio 1310 & 970"
    ,  "WISE" : "ESPN Radio 1310 & 970"
    ,  "WZGM" : "WZGM-AM"
    ,  "WTKF" : "WTKF-FM"
    ,  "WBCN" : "WBCN 1660 America's Talk"
    ,  "WFNZ" : "Sports Radio 610 The Fan"
    ,  "WZGV" : "730 ESPN"
    ,  "WSOC" : "WSOC-FM"
    ,  "WCMC" : "ESPN 99.9 The Fan"
    ,  "WQTM" : "Sportstalk 1480"
    ,  "WGHB" : "Pirate Radio 1250"
    ,  "WFNC" : "WFNC-AM"
    ,  "WFAY" : "WFAY-AM"
    ,  "WGNC" : "WGNC-AM"
    ,  "WSML" : "WSML-AM"
    ,  "WCOG" : "WCOG-AM"
    ,  "WMFR" : "WMFR-AM"
    ,  "WKRR" : "Rock 92"
    ,  "WHKP" : "WHKP-AM"
    ,  "WKVS" : "WKVS-FM"
    ,  "WAVQ" : "WAVQ-AM"
    ,  "WJNC" : "WJNC-AM"
    ,  "WRHI" : "WRHI-AM"
    ,  "WRHM" : "Interstate 107"
    ,  "WJRI" : "WJRI-AM"
    ,  "WOBX" : "WOBX-FM"
    ,  "WWNB" : "ESPN Radio 1490"
    ,  "WNOS" : "WNOS-AM"
    ,  "WCLY" : "WCLY-AM"
    ,  "WDNC" : "The Buzz 620 AM"
    ,  "WCBT" : "WCBT-AM"
    ,  "WPTM" : "WPTM-FM"
    ,  "WSAT" : "WSAT-AM"
    ,  "WSTP" : "News Radio 1490"
    ,  "WOHS" : "Real Country 1390"
    ,  "WFBX" : "WFBX-AM"
    ,  "WUKS" : "107.7 JAMZ"
    ,  "WSIC" : "WSIC-AM"
    ,  "WRGC" : "WRGC"
    ,  "WOBX" : "WOBX-AM"
    ,  "WDLX" : "Pirate Radio 930"
    ,  "WTMT" : "105.9 The Mountain"
    ,  "WSMY" : "WSMY-AM"
    ,  "WMFD" : "ESPN Radio 630"
    ,  "WKXB" : "Jammin' 99.9"
    ,  "WSJS" : "600 AM WSJS"
    ,  "KXMR" : "ESPN Radio 710 AM"
    ,  "KDAK" : "KDAK-AM"
    ,  "KDLR" : "KDLR-AM 1240"
    ,  "KDIX" : "KDIX-AM"
    ,  "KFGO" : "The Mighty 790"
    ,  "KNFL" : "KNFL-AM"
    ,  "KNOX" : "News Radio 1310"
    ,  "KGFK" : "KGFK-AM"
    ,  "KEYZ" : "News Radio 660"
    ,  "KQDJ" : "KQDJ Classic Hits 1400 AM"
    ,  "KMAV" : "KMAV 105.5 & Sports Radio 1520"
    ,  "KMSR" : "KMSR-AM"
    ,  "KRRZ" : "Classic Hits 1390"
    ,  "KVOX" : "740 The Fan"
    ,  "KDDR" : "KDDR-AM"
    ,  "KOVC" : "KOVC-AM"
    ,  "KOZN" : "1620 The Zone"
    ,  "KCSR" : "Stereo AM 610"
    ,  "KLIR" : "KLIR-FM"
    ,  "KICS" : "ESPN Radio Superstation"
    ,  "KBPY" : "KBPY-FM"
    ,  "KXPN" : "ESPN Radio Superstation"
    ,  "KLMS" : "Sports Radio 1480 KLMS"
    ,  "KBRL" : "The BIG Talker"
    ,  "KQHK" : "103.9 The Hawk"
    ,  "WJAG" : "News Talk 105.9"
    ,  "WJAG" : "News Talk 780"
    ,  "KOOQ" : "ESPN Radio 1410"
    ,  "KOIL" : "KOIL-AM 1180"
    ,  "KZOT" : "1180 The Zone 2"
    ,  "KNEB" : "KNEB 960 AM"
    ,  "WTSV" : "WTSV-AM"
    ,  "WZEI" : "WZEI-FM"
    ,  "WTSN" : "WTSN AM 1270"
    ,  "WSAK" : "102.1 The Shark"
    ,  "WTSL" : "WTSL-AM"
    ,  "WTPL" : "107.7 The Pulse"
    ,  "WZBK" : "WZBK-AM"
    ,  "WXXK" : "Kixx FM"
    ,  "WGHM" : "WGAM The Game 1250 & 900"
    ,  "WGAM" : "WGAM The Game 1250 & 900"
    ,  "WMYF" : "The Sports Animal"
    ,  "WHEB" : "100.3 WHEB The Rock Station"
    ,  "WPKX" : "WPKX-AM"
    ,  "WLKZ" : "104.9 The Hawk"
    ,  "WENJ" : "ESPN 1450"
    ,  "WENJ" : "97.3 ESPN"
    ,  "WPGG" : "WPG Talk Radio 1450"
    ,  "WNYM" : "WNYM-AM"
    ,  "WNJE" : "920 The Jersey"
    ,  "KNMZ" : "103.7 ESPN"
    ,  "KNML" : "610 AM: The Sports Animal"
    ,  "KIVA" : "1600 The Rock of Talk"
    ,  "KQTM" : "101.7 The Team"
    ,  "KALY" : "JENNiRADIO"
    ,  "KCQL" : "Fox Sports Radio 1340"
    ,  "KCLV" : "KCLV-AM"
    ,  "KYVA" : "Real Country AM 1230"
    ,  "KYVA" : "Oldies 103.7"
    ,  "KHOB" : "ESPN 1390 AM"
    ,  "KSNM" : "KSNM 570 AM"
    ,  "KGRT" : "Classic Country KGRT"
    ,  "KWML" : "Fox Sports 570"
    ,  "KTBL" : "KTBL-AM"
    ,  "KWMW" : "KWMW-FM"
    ,  "KRUI" : "KRUI-AM"
    ,  "KVSF" : "KVSF-AM"
    ,  "KBAD" : "FOX Sports Radio 920"
    ,  "KWWN" : "ESPN Radio 1100 & 98.9 FM"
    ,  "KRLV" : "KRLV-AM"
    ,  "KPLY" : "KPLY-AM"
    ,  "KUUB" : "Reno's ESPN Radio 94.5 FM"
    ,  "KHIT" : "KHIT-AM"
    ,  "KFOY" : "KFOY-AM"
    ,  "KWNA" : "KWNA-AM"
    ,  "KWNA" : "KWNA-FM"
    ,  "WTMM" : "104.5 The Team"
    ,  "WPYX" : "PYX 106"
    ,  "WGY" : "WGY-AM"
    ,  "WGY" : "WGY-FM"
    ,  "WAUB" : "Finger Lakes News Radio"
    ,  "WABH" : "The Sports Giant ESPN Radio"
    ,  "WAAL" : "99.1 The Whale"
    ,  "WENE" : "Fox Sports 1430"
    ,  "WTKW" : "TK 99"
    ,  "WBEN" : "WBEN NewsRadio 930"
    ,  "WWKB" : "KB 1520"
    ,  "WGR" : "WGR 550 Sports Radio"
    ,  "WEDG" : "WEDG-FM"
    ,  "WSDE" : "WSDE-AM"
    ,  "WDOE" : "WDOE-AM"
    ,  "WELM" : "WELM 1410 AM"
    ,  "WGVA" : "WGVA-AM"
    ,  "WENT" : "AM 1340 WENT"
    ,  "WPIE" : "1160 ESPN Ithaca"
    ,  "WJTN" : "WJTN News Talk 1240"
    ,  "WKSN" : "Kissin' Oldies"
    ,  "WIXT" : "WIXT-AM"
    ,  "WLVL" : "WLVL-AM"
    ,  "WFAN" : "Sports Radio 66 The Fan"
    ,  "WBBR" : "WBBR-AM"
    ,  "WCBS" : "WCBS 880"
    ,  "WEPN" : "ESPN 1050 AM"
    ,  "WEPN" : "ESPN New York 98.7"
    ,  "WFAN" : "101.9 FM The Fan"
    ,  "WNBM" : "WNBM-FM"
    ,  "WACK" : "1420 Wack"
    ,  "WGNY" : "WGNY-AM"
    ,  "WHLD" : "Sports Radio 1270"
    ,  "WTLA" : "WTLA-AM"
    ,  "WSLB" : "WSLB-AM"
    ,  "WHDL" : "WHDL-AM"
    ,  "WSGO" : "WSGO-AM"
    ,  "WEAV" : "960 The Zone"
    ,  "WIRY" : "WIRY-AM"
    ,  "WHTK" : "1280 WHTK"
    ,  "WHAM" : "1180 WHAM"
    ,  "WOKR" : "The Team"
    ,  "WRSB" : "The Team"
    ,  "WRNY" : "WRNY-AM"
    ,  "WPTR" : "Sporty 1240"
    ,  "WHTK" : "FM 107.3"
    ,  "WENU" : "WENU-AM"
    ,  "WSKO" : "The Score 1260"
    ,  "WSYR" : "News Radio 570"
    ,  "WSYR" : "News Radio 106.9"
    ,  "WZUN" : "WZUN-FM"
    ,  "WOFX" : "FOX Sports 980"
    ,  "WIBX" : "WIBX 950"
    ,  "WTLB" : "WTLB-AM"
    ,  "WARF" : "FOX Sports Radio 1350"
    ,  "WAKR" : "WAKR-AM"
    ,  "WOHF" : "WOHF-FM"
    ,  "WRQK" : "Rock 106.9"
    ,  "WSAI" : "FOX Sports 1360"
    ,  "WLW" : "700 WLW"
    ,  "WCKY" : "Cincinnati's ESPN 1530"
    ,  "WKNR" : "ESPN Cleveland"
    ,  "WWGK" : "ESPN Cleveland"
    ,  "WKRK" : "Sports Radio 92.3 The Fan"
    ,  "WBNS" : "1460 ESPN"
    ,  "WBNS" : "Sports Radio 97.1 The Fan"
    ,  "WVOH" : "95.5 The Game"
    ,  "WTNS" : "WTNS-FM"
    ,  "WING" : "ESPN Radio 1410"
    ,  "WONE" : "980 WONE"
    ,  "WTUE" : "104.7 WTUE"
    ,  "WFIN" : "WFIN-AM"
    ,  "WXBW" : "Big Buck Country"
    ,  "WWSR" : "93.1 The Fan"
    ,  "WCIT" : "Sports Talk 940"
    ,  "WRGM" : "ESPN Radio 1440"
    ,  "WMAN" : "WMAN-AM"
    ,  "WNCO" : "Fox Sports 1340"
    ,  "WVNO" : "WVNO-FM"
    ,  "WJAW" : "ESPN Radio 100.9"
    ,  "WMOA" : "WMOA 1490 Radio"
    ,  "WMPO" : "WMPO-AM"
    ,  "WNIO" : "The Sports Animal"
    ,  "WSOM" : "Talk Radio 600"
    ,  "WJAW" : "630 ESPN"
    ,  "WLQR" : "106.5 The Ticket"
    ,  "WSPD" : "News Talk 1370"
    ,  "WCWA" : "Fox Sports Radio 1230"
    ,  "WIOT" : "104.7 WIOT"
    ,  "WLQR" : "Talk Radio 1470"
    ,  "WXKR" : "94.5 XKR"
    ,  "WTOD" : "TalkRadio 1470"
    ,  "WTOD" : "WTOD-FM"
    ,  "WQQO" : "Q105.5"
    ,  "WBTC" : "WBTC-AM"
    ,  "WQKT" : "104.5 WQKT Sports Country"
    ,  "WBBW" : "Sports Radio 1240"
    ,  "WWIZ" : "Real Rock 104"
    ,  "WHIZ" : "AM 1240"
    ,  "KWON" : "KWON-AM"
    ,  "KOKB" : "Triple Play Sports Radio"
    ,  "KCLI" : "NewsTalk KCLI"
    ,  "KADS" : "The Sports Animal"
    ,  "KCRC" : "CTB Sports"
    ,  "KQOB" : "96.9 BOB FM"
    ,  "KGYN" : "U.S. Country"
    ,  "KINB" : "KINB-FM"
    ,  "KXCA" : "The Ticket"
    ,  "KKRX" : "KKRX-AM"
    ,  "KWPN" : "ESPN Radio 640"
    ,  "WWLS" : "The Sports Animal"
    ,  "WWLS" : "The Sports Animal"
    ,  "KBRU" : "94.7 The Brew"
    ,  "KGHM" : "1340 The Game"
    ,  "KRXO" : "KRXO-FM"
    ,  "KEBC" : "Comedy 1560"
    ,  "KPGM" : "KPGM-AM"
    ,  "KOSB" : "Triple Play Sports Radio"
    ,  "KOKP" : "Triple Play Sports Radio"
    ,  "WBBZ" : "WBBZ-AM"
    ,  "KMMY" : "MY ROCK 96.5"
    ,  "KYAL" : "AM 1550 KYAL-AM"
    ,  "KYAL" : "97.1 FM The Sports Animal"
    ,  "KGND" : "KGND-AM"
    ,  "KITO" : "KITO-FM"
    ,  "KWEY" : "KWEY-FM"
    ,  "KWEY" : "KWEY-AM"
    ,  "KSIW" : "KSIW-AM"
    ,  "KTMT" : "ESPN 580"
    ,  "KKEE" : "KVAS-AM"
    ,  "KKBC" : "KKBC-FM"
    ,  "KICE" : "SportsRadio 940"
    ,  "KHSN" : "ESPN Radio 1230"
    ,  "KEJO" : "1240 Joe Radio"
    ,  "KTHH" : "Comedy 990 AM"
    ,  "KRJT" : "KRJT-FM"
    ,  "KPNW" : "News Radio 1120"
    ,  "KUJZ" : "95.3 The Score"
    ,  "KGCL" : "KGCL-FM"
    ,  "KLAD" : "KLAD-AM"
    ,  "KGAL" : "NewsTalk 1580"
    ,  "KEDO" : "KEDO-AM"
    ,  "KQSO" : "KQSO-FM"
    ,  "KCUP" : "KCUP-AM 1230"
    ,  "KTIX" : "KTIX-AM"
    ,  "KCMX" : "Newstalk 880"
    ,  "KFXX" : "1080 The Fan"
    ,  "KWJJ" : "99.5 The Wolf"
    ,  "KUFO" : "Freedom 970"
    ,  "KXL" : "FM News 101"
    ,  "KXTG" : "750 The Game"
    ,  "KRCO" : "KRCO-AM"
    ,  "KSKR" : "FOX Sports Radio 1490 The Score"
    ,  "KWOD" : "1390 The Fan"
    ,  "KYKN" : "KYKN-AM"
    ,  "KCRX" : "The Classic Rock Station"
    ,  "KICE" : "Fox Sports Central Oregon"
    ,  "KVBL" : "KVBL-FM"
    ,  "KWLZ" : "KWLZ-FM"
    ,  "WTKZ" : "ESPN Sports Radio 1320"
    ,  "WBYN" : "WBYN-AM"
    ,  "WMBA" : "WMBA-AM"
    ,  "WBVP" : "WBVP-AM"
    ,  "WESB" : "WESB NewsRadio 1490"
    ,  "WEEO" : "WEEO-AM"
    ,  "WIOO" : "Classic Country"
    ,  "WCCR" : "C93"
    ,  "WHYP" : "Cool 1370"
    ,  "WWCB" : "WWCB-AM"
    ,  "WEEX" : "ESPN Sports Radio 1230/ 1320"
    ,  "WCTO" : "Cat Country 96.1"
    ,  "WGGE" : "The Edge"
    ,  "WBYB" : "WBYB-FM"
    ,  "WPDC" : "Sporting News Radio 1600"
    ,  "WPSE" : "WPSE-AM"
    ,  "WQHZ" : "Z 102.3"
    ,  "WRIE" : "Sports Radio 1260 The Score"
    ,  "WQFM" : "NEPA's ESPN Radio 630-1240"
    ,  "WFRA" : "WFRA-AM"
    ,  "WGET" : "Fox Sports 1320"
    ,  "WTKT" : "1460 The Ticket"
    ,  "WHGB" : "Sports Radio 1400"
    ,  "WQXA" : "105.7 The X"
    ,  "WHUN" : "ESPN Radio 1150"
    ,  "WQMU" : "U-92"
    ,  "WDAD" : "WDAD-AM"
    ,  "WJSA" : "WJSA-AM"
    ,  "WKGE" : "The Edge"
    ,  "WWGE" : "The Edge"
    ,  "WLPA" : "FOX Sports Radio 1490 AM"
    ,  "WCNS" : "WCNS-AM"
    ,  "WBCB" : "WBCB-AM"
    ,  "WVLY" : "The Valley"
    ,  "WGLD" : "Sports Radio 1440"
    ,  "WEEO" : "WEEO-FM"
    ,  "WMGW" : "WMGW-AM"
    ,  "WWKL" : "Hot 93.5"
    ,  "WLLF" : "Sports Radio 96.7"
    ,  "WJUN" : "ESPN Radio 1220"
    ,  "WJUN" : "Country 92.5"
    ,  "WEGH" : "WEGH-FM 107.3"
    ,  "WIP" : "Sportsradio 94WIP"
    ,  "WPHT" : "Talk Radio 1210 WPHT"
    ,  "WIP" : "WIP-FM"
    ,  "WPEN" : "97.5 The Fanatic"
    ,  "WPEN" : "WPEN-AM"
    ,  "KWY" : "Newsradio 1060"
    ,  "KDKA" : "93.7 The Fan"
    ,  "KQV" : "KQV AM 1410"
    ,  "KDKA" : "NewsRadio 1020"
    ,  "WBGG" : "WBGG-AM"
    ,  "WHBS" : "The Sports Hub"
    ,  "WPPA" : "WPPA-AM"
    ,  "WEEU" : "830 AM Sports"
    ,  "WIOV" : "Sports Radio 1240"
    ,  "WSOX" : "WSOX-FM"
    ,  "WEJL" : "NEPA's ESPN Radio 630-1240"
    ,  "WBAX" : "NEPA's ESPN Radio 630-1240"
    ,  "WMQX" : "Max 102"
    ,  "WARM" : "Sports Radio 590 WARM"
    ,  "WEJL" : "WEJL-FM"
    ,  "WQWK" : "ESPN Radio 1450"
    ,  "WRSC" : "1390 The Fanatic"
    ,  "WKOK" : "Newsradio 1070"
    ,  "WTIV" : "WTIV-AM"
    ,  "WTTC" : "ESPN Radio 1550"
    ,  "WTZN" : "The Zone"
    ,  "WMBS" : "Your Local Station 590 AM WMBS"
    ,  "WJPA" : "WJPA Radio"
    ,  "WBSX" : "97.9 X"
    ,  "WLYC" : "ESPN Williamsport"
    ,  "WEJS" : "WEJS-AM"
    ,  "WOYK" : "WOYK-AM 1350"
    ,  "WABV" : "WABV-AM"
    ,  "WROP" : "WROP-AM"
    ,  "WPUB" : "Kool 102.7"
    ,  "WSPO" : "For Sports Radio 1390"
    ,  "WQNT" : "WQNT-AM"
    ,  "WWIK" : "ESPN Charleston"
    ,  "WQSC" : "WQSC-AM"
    ,  "WVSZ" : "Interstate 107"
    ,  "WCCP" : "104.9 Talk.Sports"
    ,  "WXBT" : "560 The Team"
    ,  "WNKT" : "107.5 The Game"
    ,  "WISW" : "1320 The Fan "
    ,  "WHSC" : "WHSC-AM"
    ,  "WDSC" : "WDSC-AM"
    ,  "WWFN" : "100.1 The Fan"
    ,  "WGVL" : "ESPN 1440"
    ,  "WYRD" : "WYRD-AM"
    ,  "WYRD" : "WYRD-FM"
    ,  "WYMB" : "WYMB-AM"
    ,  "WSEA" : "Sports Radio 100.3 The Team"
    ,  "WSPG" : "ESPN Spartanburg 1400"
    ,  "WORD" : "WORD-AM"
    ,  "KBFS" : "KBFS 1450 AM"
    ,  "KOKK" : "1210 AM KOKK"
    ,  "KCCR" : "Today's KCCR AM 1240"
    ,  "KOTA" : "Radio 1380 KOTA"
    ,  "KTOQ" : "ESPN Rapid City"
    ,  "KWSN" : "Sports Radio KWSN AM 1230"
    ,  "KYDT" : "KYDT 103.1 FM"
    ,  "KVTK" : "ESPN Radio 1570"
    ,  "KWAT" : "KWAT-AM"
    ,  "WXSM" : "640 The Xtreme Sports Monster"
    ,  "WUCZ" : "104.1 The Ranch"
    ,  "WDEF" : "FOX Sports Radio 1370 AM"
    ,  "WALV" : "ESPN Chattanooga"
    ,  "WKFN" : "WKFN-AM"
    ,  "WPTN" : "The Eagle 780"
    ,  "WATX" : "WATX-AM"
    ,  "WBXE" : "Rock 93.7"
    ,  "WUCT" : "WUCT-AM"
    ,  "WEMB" : "The Legend"
    ,  "WNML" : "The Sports Animal"
    ,  "WQZQ" : "Sports Talk 830"
    ,  "WHOP" : "Lite 98.7"
    ,  "WNWS" : "101.5 FM News/Talk WNWS"
    ,  "WDHM" : "WDHM-AM"
    ,  "WQUT" : "WQUT-FM"
    ,  "WVLZ" : "Tennessee Sports Radio"
    ,  "WNML" : "The Sports Animal"
    ,  "WOKI" : "News Talk 98.7"
    ,  "WKGN" : "Sports Radio Knoxville"
    ,  "WDXE" : "Mix 106"
    ,  "WWLX" : "WWLX-AM"
    ,  "WRKQ" : "1250 The Authority"
    ,  "WDXE" : "Classic Country"
    ,  "WMSR" : "Thunder Radio"
    ,  "WMSR" : "Thunder Radio"
    ,  "WCMT" : "Mix 101.3"
    ,  "WAKI" : "WAKI-AM"
    ,  "WMC" : "Sports 790"
    ,  "WMFS" : "ESPN Radio"
    ,  "WMFS" : "ESPN Radio 92.9"
    ,  "WHBQ" : "Sports 56"
    ,  "WPGF" : "WPGF-FM"
    ,  "WNFN" : "106 Hits"
    ,  "WGFX" : "104.5 The Zone"
    ,  "WNSR" : "Sportsradio 560"
    ,  "WNTC" : "Nashville Sports Radio"
    ,  "WPRT" : "102.5 The Game"
    ,  "WBUZ" : "102.9 The Buzz"
    ,  "WMUF" : "Today's Best Country"
    ,  "WRQR" : "WRQR-AM"
    ,  "WKSR" : "WKSR-AM"
    ,  "WKSR" : "WKSR-FM"
    ,  "WSDT" : "WSDT-AM"
    ,  "WECO" : "WECO Radio"
    ,  "KQPN" : "730 Fox Sports"
    ,  "KTLT" : "Sports Radio 98.1"
    ,  "KVLF" : "Voice of the Last Frontier"
    ,  "KGNC" : "NewsTalk 710"
    ,  "KPUR" : "KPUR-AM"
    ,  "KZRK" : "Rock 108"
    ,  "KVET" : "AM 1300 The Zone"
    ,  "KTXX" : "104.9 The Horn"
    ,  "KZNX" : "ESPN Radio 1530"
    ,  "KWNX" : "ESPN Austin"
    ,  "KLGO" : "KLGO-AM"
    ,  "KBYG" : "KBYG-AM"
    ,  "KQTY" : "KQTY Radio"
    ,  "KXYL" : "KXYL-AM"
    ,  "KXYL" : "KXYL-FM"
    ,  "KTON" : "KTON-AM"
    ,  "KGAS" : "KGAS Radio 1590 AM"
    ,  "KGAS" : "KGAS Radio 104.3 FM"
    ,  "KXCS" : "KXCS-FM"
    ,  "KZNE" : "The Zone"
    ,  "KSIX" : "Sports Radio 1230"
    ,  "KRLD" : "105.3 The Fan"
    ,  "KRLD" : "News Radio 1080"
    ,  "KTCK" : "The Ticket"
    ,  "KESN" : "ESPN Radio Dallas"
    ,  "KLIF" : "KLIF-AM"
    ,  "KROD" : "600 AM ESPN El Paso"
    ,  "KTCK" : "The Ticket"
    ,  "KPIR" : "KPIR-AM"
    ,  "KWRD" : "1470 AM"
    ,  "KPXI" : "Real Country KPXI"
    ,  "KBME" : "Sportstalk 790"
    ,  "KILT" : "SportsRadio 610"
    ,  "KFNC" : "ESPN 97.5"
    ,  "KGOW" : "Yahoo! Sports Radio 1560"
    ,  "KIKK" : "CBS Sports Radio 650"
    ,  "KHLE" : "KHLE-FM"
    ,  "KKAM" : "1340 The Fan"
    ,  "KJTV" : "AM950"
    ,  "KTTU" : "Double T 104.3"
    ,  "KSML" : "KSML-AM"
    ,  "KMHT" : "1450 ESPN Radio"
    ,  "KMHT" : "103.9 FM KMHT"
    ,  "KURV" : "News Talk 710"
    ,  "KLRK" : "KLRK-AM"
    ,  "KNFM" : "LoneStar 92"
    ,  "KBAT" : "KBAT-FM"
    ,  "KVJY" : "KVJY-AM"
    ,  "KPYN" : "KPYN-AM"
    ,  "KKSA" : "KKSA 1260 AM"
    ,  "KGKL" : "News Talk 960"
    ,  "KTKR" : "Ticket 760"
    ,  "WOAI" : "News Radio 1200"
    ,  "KRPT" : "KRPT-FM"
    ,  "KONO" : "Sports Radio 860"
    ,  "KZDC" : "ESPN San Antonio"
    ,  "KTAE" : "The Lonestar Legend"
    ,  "KKTK" : "Fox Sports 1400"
    ,  "KTBB" : "KTTB-AM"
    ,  "KTTB" : "KTTB-FM"
    ,  "KRWR" : "ESPN 92.1"
    ,  "KYKX" : "KYKX"
    ,  "KRZI" : "1660 ESPN Radio"
    ,  "KXPN" : "ESPN Radio 95.5"
    ,  "KGUM" : "KGUM"
    ,  "KGUM" : "The Cat 105 Guam"
    ,  "WVWI" : "RADIO ONE AM 1000"
    ,  "WOSO" : "WOSO"
    ,  "KMXD" : "KMXD-FM"
    ,  "KOAL" : "KOAL-AM"
    ,  "KOVO" : "KOVO-AM 960"
    ,  "KSVC" : "KSVC-AM"
    ,  "KQSW" : "KQSW-FM"
    ,  "KRKK" : "KRKK-AM"
    ,  "KFNZ" : "1320 K-Fan"
    ,  "KZNS" : "Fox Sports Radio 97.5"
    ,  "KZNS" : "1280 The Zone"
    ,  "KUNF" : "Sports Radio 1210 AM"
    ,  "KHKR" : "Sports Radio 1210"
    ,  "WBLT" : "1350 ESPN Bedford"
    ,  "WKEX" : "ESPN Blacksburg"
    ,  "WBRW" : "105.3 The Bear"
    ,  "WWXX" : "ESPN Radio 94.3"
    ,  "WKAV" : "SportsRadio 1400"
    ,  "WCHV" : "WCHV-AM"
    ,  "WCHV" : "WCHV-FM"
    ,  "WIQO" : "WIQO-FM"
    ,  "WNTX" : "WNTX-AM"
    ,  "WFTR" : "NBC Sports Radio 1450"
    ,  "WZEZ" : "WZEZ-FM"
    ,  "WMNA" : "106.3 ESPN Danville"
    ,  "WMNA" : "WMNA-AM"
    ,  "WSVA" : "WSVA"
    ,  "WBOP" : "95.5 The Zone"
    ,  "WHBG" : "ESPN HARRISONBURG"
    ,  "WHAP" : "FOX Sports Radio 1340"
    ,  "WWZW" : "WWZW-FM"
    ,  "WMVA" : "Great Radio AM 1450"
    ,  "WODY" : "WODY-AM"
    ,  "WSVG" : "Sports Radio WSVG 790 AM"
    ,  "WGH" : "Star 1310"
    ,  "WTAR" : "AM 850 WTAR"
    ,  "WTPS" : "NEWS TALK 1240"
    ,  "WWBU" : "Super Sports 101.7"
    ,  "WXGI" : "ESPN 950 AM"
    ,  "WRNL" : "Sports Radio 910"
    ,  "WRXL" : "102.1 The X"
    ,  "WGMN" : "1240 ESPN Roanoke"
    ,  "WFIR" : "News/ Talk 960 AM"
    ,  "WVGM" : "1240 ESPN Roanoke"
    ,  "WXLZ" : "WXLZ-AM"
    ,  "WTON" : "ESPN 1240 The Boss"
    ,  "WXTG" : "The Game"
    ,  "WXTG" : "The Game"
    ,  "WVSP" : "ESPN Radio 94.1"
    ,  "WAMM" : "WAMM-AM"
    ,  "WSNO" : "WSNO 1450 AM"
    ,  "WEXP" : "101.5 The Fox"
    ,  "WTSA" : "ESPN 1450 The Ticket"
    ,  "WCPV" : "101.3 ESPN Radio"
    ,  "WMOO" : "MOO 92"
    ,  "WIKE" : "WIKE-AM"
    ,  "WDVT" : "94.5 The Drive"
    ,  "WEEY" : "WEEY-FM"
    ,  "WSTJ" : "WSTJ-AM"
    ,  "WKKN" : "WKKN-FM"
    ,  "WMXR" : "WMXR-FM"
    ,  "KWLE" : "1340 The Whale"
    ,  "KPUG" : "1170 The Sports Leader"
    ,  "KELA" : "KELA-AM"
    ,  "KMNT" : "KMNT-FM"
    ,  "KCLK" : "KCLK-AM"
    ,  "KMAX" : "KMAX-AM"
    ,  "KCRK" : "KCRK-FM"
    ,  "KXLE" : "KXLE-AM"
    ,  "KRKO" : "KRKO-AM"
    ,  "KFKB" : "KFKB-AM"
    ,  "KWOK" : "KWOK-AM"
    ,  "KWIQ" : "ESPN Radio 1020"
    ,  "KAPS" : "KAPS Country"
    ,  "KIT" : "News Talk KIT"
    ,  "KGY" : "AM 1240 KGY"
    ,  "KNCW" : "KNCW-FM"
    ,  "KONA" : "610 KONA Information Radio"
    ,  "KONP" : "KONP-AM"
    ,  "KJR" : "950 KJR"
    ,  "KNBQ" : "Sports Radio 102.9 KJR"
    ,  "KFNQ" : "1090 The Fan"
    ,  "KMAS" : "Newsradio 1030"
    ,  "KGA" : "Sports Radio 1510"
    ,  "KEYF" : "KEYF-AM"
    ,  "KJRB" : "790 KJRB News and Talk"
    ,  "KZFS" : "1280 Fox Sports"
    ,  "KKZX" : "KKZX-FM"
    ,  "KXLX" : "700 ESPN"
    ,  "KQNT" : "590 KQNT"
    ,  "KHHO" : "KHHO-AM"
    ,  "KKSN" : "KKSN-AM"
    ,  "KTEL" : "ESPN Radio 1490"
    ,  "KKRT" : "ESPN Radio 900"
    ,  "KJOX" : "ESPN Radio 1390"
    ,  "KUTI" : "1460 ESPN Radio"
    ,  "KIT" : "News Talk KIT"
    ,  "WACD" : "Country 106"
    ,  "WAPL" : "Wisconsin's Rock Station"
    ,  "WOTE" : "WOTE-AM"
    ,  "WBSZ" : "Z93"
    ,  "WJJH" : "J-96 Rock"
    ,  "WBEV" : "WBEV 1430 AM"
    ,  "WJMQ" : "Frog Country"
    ,  "WBIZ" : "Sports Radio 1400"
    ,  "WFON" : "K-107"
    ,  "KFIZ" : "News Talk 1450 KFIZ "
    ,  "WFAW" : "940 WFAW"
    ,  "WNFL" : "WNFL 1440"
    ,  "WDUZ" : "The Fan"
    ,  "WDUZ" : "The Fan"
    ,  "WSCO" : "AM 1570 The Score"
    ,  "WRLS" : "Vacationland Radio"
    ,  "WHSM" : "WHSM-AM"
    ,  "WNXR" : "WNXR-FM"
    ,  "WHBY" : "News Talk 1150 WHBY"
    ,  "WKTY" : "580 WKTY"
    ,  "WLDY" : "WLDY-AM"
    ,  "WGLR" : "ESPN 1280"
    ,  "WTLX" : "100.5 ESPN Madison"
    ,  "WIBA" : "Newstalk 1310"
    ,  "WTTN" : "WTTN-AM"
    ,  "WXXM" : "92.1 The Mic"
    ,  "WIBA" : "WIBA-FM"
    ,  "WOMT" : "WOMT 1240 AM"
    ,  "WLST" : "Cat Country"
    ,  "WMAM" : "ESPN Radio 570"
    ,  "WOSQ" : "SportsRadio 92.3 WOSQ"
    ,  "WMEQ" : "NewsTalk AM 880"
    ,  "WISN" : "News Talk 1130"
    ,  "WOKY" : "920 AM The Wolf"
    ,  "WAUK" : "540 ESPN"
    ,  "WQPC" : "Q 94 FM Great Country"
    ,  "WRJN" : "News Talk 1400"
    ,  "WJMC" : "WJMC-AM"
    ,  "WRPN" : "News Talk Radio WRPN"
    ,  "WEVR" : "WEVR-AM"
    ,  "WDTX" : "ESPN Sports Fan 100.5"
    ,  "WOWN" : "B99.3"
    ,  "WTCH" : "Moose Country"
    ,  "WHBL" : "News Radio 1330"
    ,  "WCLB" : "WCLB-AM"
    ,  "WXCX" : "WXCX-FM"
    ,  "WSRG" : "97.7 The Big Dawg"
    ,  "WTSO" : "WTSO-AM "
    ,  "WCYE" : "Coyote 93.7"
    ,  "WJJQ" : "WJJQ 92.5 FM Radio"
    ,  "WVRQ" : "WVRQ AM 1360"
    ,  "WRRD" : "WRRD-AM"
    ,  "WDUX" : "WDUX FM 92.7"
    ,  "WFHR" : "AM 1320 WFHR"
    ,  "WJLS" : "WJLS-AM"
    ,  "WHKX" : "Kicks Country"
    ,  "WBUC" : "WBUC"
    ,  "WCHS" : "WCHS Radio 58"
    ,  "WSWW" : "WSWW-FM"
    ,  "WBTQ" : "93.5 BTQ"
    ,  "WBRB" : "The Bear 101.3"
    ,  "WDNE" : "WDNE"
    ,  "WDNE" : "WDNE 99"
    ,  "WELK" : "94.7 WELK"
    ,  "WMMN" : "FOX Sports Radio 920 WMMN"
    ,  "WRLF" : "94 Rock"
    ,  "WTCS" : "The Talk of Fairmont"
    ,  "WMTD" : "ESPN 102.3 The Ticket"
    ,  "WRVC" : "Huntington Super Talk"
    ,  "WMGA" : "WMGA-FM"
    ,  "WKLP" : "ESPN Radio 1390"
    ,  "WVOW" : "WVOW 101.9."
    ,  "WVOW" : "WVOW 1290"
    ,  "WRNR" : "Talk Radio  WRNR AM 740"
    ,  "WMON" : "WMON-AM"
    ,  "WAJR" : "WAJR"
    ,  "WVAQ" : "WVAQ-FM"
    ,  "WAJR" : "WAJR-FM"
    ,  "WWLW" : "Magic 106.5"
    ,  "WXCR" : "WXCR-FM"
    ,  "WMOV" : "WMOV-AM"
    ,  "WJYP" : "WJYP-AM"
    ,  "WEIR" : "Sports Radio 1430"
    ,  "WKKX" : "WKKX-AM"
    ,  "WSLW" : "The Red Zone"
    ,  "KKTL" : "AM 1400 ESPN"
    ,  "KVOC" : "KVOC-AM"
    ,  "KMLD" : "KMLD-FM"
    ,  "KFBC" : "KFBC"
    ,  "KTAG" : "KTAG-FM"
    ,  "KKTY" : "KKTY-AM"
    ,  "KEVA" : "1240 KEVA"
    ,  "KXXL" : "KXXL-FM"
    ,  "KZJH" : "KZJH-FM"
    ,  "KOVE" : "KOVE-AM"
    ,  "KOWB" : "KOWB 1290"
    ,  "KWYW" : "KWYW-FM"
    ,  "KASL" : "KASL-AM"
    ,  "KPOW" : "KPOW-AM"
    ,  "KSHW" : "KSHW-FM"
    ,  "KYCN" : "KYCN 1340 AM"
    ,  "KWOR" : "AM 1340 K-WOR"
    }

def get_aka_sign(call_sign):
    if call_sign in aka_call_signs:
        return aka_call_signs[call_sign]
    else:
        return call_sign
